# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Weather' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Weather
    pod 'Macaw', '0.9.0'
	pod 'DynamicColor', '~> 3.3'

# Cooking project for XCode9 and Swift 4
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
