workspace 'Weather.workspace'
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'

target 'Weather' do
  use_frameworks!
  pod 'Macaw', '0.9.10'
	pod 'DynamicColor'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0' then
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
